### ISSUE TITLE
Getting error while deploying 

### ISSUE THREAD

**Issue by Ash-333** [render-examples/strapi-sqlite#28]
Jan 26 10:24:16 PM  Error: The public folder (/data/public) doesn't exist or is not accessible. Please make sure it exists.
Jan 26 10:24:16 PM      at module.exports (/opt/render/project/src/node_modules/@strapi/strapi/lib/core/bootstrap.js:29:11)
Jan 26 10:24:16 PM      at async Strapi.register (/opt/render/project/src/node_modules/@strapi/strapi/lib/Strapi.js:383:5)
Jan 26 10:24:16 PM      at async Strapi.load (/opt/render/project/src/node_modules/@strapi/strapi/lib/Strapi.js:477:5)
Jan 26 10:24:16 PM      at async Strapi.start (/opt/render/project/src/node_modules/@strapi/strapi/lib/Strapi.js:212:9)
Jan 26 10:24:16 PM  error Command failed with exit code 1.

**Comment by Fvtvl** [comment]
i have the same problem

**Comment by p-mylecharane** [comment]
Same as above

**Comment by tristanpn02** [comment]
Any updates on this?
I'm getting the same issue

**Comment by muriukialex** [comment]
I also have the same problem
There seems to be an issue while deploying strapi on render @zach-render

**Comment by akunify** [comment]
i have the same problem and solve this, 
this issue will be solve after upgrade strapi version to `4.1.7`

**Comment by martinchristov** [comment]
Same issue. 
https://community.render.com/t/keep-getting-same-error-when-trying-to-deploy-a-strapi-app/5845
Even if you remove the data commands it keeps failing.

Render claims to have a free plan, but you don't seem being able to even start for free.
